logo = """                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                              
        GGGGGGGGGGGGGUUUUUUUU     UUUUUUUUEEEEEEEEEEEEEEEEEEEEEE   SSSSSSSSSSSSSSS    SSSSSSSSSSSSSSS      TTTTTTTTTTTTTTTTTTTTTTTHHHHHHHHH     HHHHHHHHHEEEEEEEEEEEEEEEEEEEEEE     NNNNNNNN        NNNNNNNNUUUUUUUU     UUUUUUUUMMMMMMMM               MMMMMMMMBBBBBBBBBBBBBBBBB   EEEEEEEEEEEEEEEEEEEEEERRRRRRRRRRRRRRRRR   
     GGG::::::::::::GU::::::U     U::::::UE::::::::::::::::::::E SS:::::::::::::::S SS:::::::::::::::S     T:::::::::::::::::::::TH:::::::H     H:::::::HE::::::::::::::::::::E     N:::::::N       N::::::NU::::::U     U::::::UM:::::::M             M:::::::MB::::::::::::::::B  E::::::::::::::::::::ER::::::::::::::::R  
   GG:::::::::::::::GU::::::U     U::::::UE::::::::::::::::::::ES:::::SSSSSS::::::SS:::::SSSSSS::::::S     T:::::::::::::::::::::TH:::::::H     H:::::::HE::::::::::::::::::::E     N::::::::N      N::::::NU::::::U     U::::::UM::::::::M           M::::::::MB::::::BBBBBB:::::B E::::::::::::::::::::ER::::::RRRRRR:::::R 
  G:::::GGGGGGGG::::GUU:::::U     U:::::UUEE::::::EEEEEEEEE::::ES:::::S     SSSSSSSS:::::S     SSSSSSS     T:::::TT:::::::TT:::::THH::::::H     H::::::HHEE::::::EEEEEEEEE::::E     N:::::::::N     N::::::NUU:::::U     U:::::UUM:::::::::M         M:::::::::MBB:::::B     B:::::BEE::::::EEEEEEEEE::::ERR:::::R     R:::::R
 G:::::G       GGGGGG U:::::U     U:::::U   E:::::E       EEEEEES:::::S            S:::::S                 TTTTTT  T:::::T  TTTTTT  H:::::H     H:::::H    E:::::E       EEEEEE     N::::::::::N    N::::::N U:::::U     U:::::U M::::::::::M       M::::::::::M  B::::B     B:::::B  E:::::E       EEEEEE  R::::R     R:::::R
G:::::G               U:::::D     D:::::U   E:::::E             S:::::S            S:::::S                         T:::::T          H:::::H     H:::::H    E:::::E                  N:::::::::::N   N::::::N U:::::D     D:::::U M:::::::::::M     M:::::::::::M  B::::B     B:::::B  E:::::E               R::::R     R:::::R
G:::::G               U:::::D     D:::::U   E::::::EEEEEEEEEE    S::::SSSS          S::::SSSS                      T:::::T          H::::::HHHHH::::::H    E::::::EEEEEEEEEE        N:::::::N::::N  N::::::N U:::::D     D:::::U M:::::::M::::M   M::::M:::::::M  B::::BBBBBB:::::B   E::::::EEEEEEEEEE     R::::RRRRRR:::::R 
G:::::G    GGGGGGGGGG U:::::D     D:::::U   E:::::::::::::::E     SS::::::SSSSS      SS::::::SSSSS                 T:::::T          H:::::::::::::::::H    E:::::::::::::::E        N::::::N N::::N N::::::N U:::::D     D:::::U M::::::M M::::M M::::M M::::::M  B:::::::::::::BB    E:::::::::::::::E     R:::::::::::::RR  
G:::::G    G::::::::G U:::::D     D:::::U   E:::::::::::::::E       SSS::::::::SS      SSS::::::::SS               T:::::T          H:::::::::::::::::H    E:::::::::::::::E        N::::::N  N::::N:::::::N U:::::D     D:::::U M::::::M  M::::M::::M  M::::::M  B::::BBBBBB:::::B   E:::::::::::::::E     R::::RRRRRR:::::R 
G:::::G    GGGGG::::G U:::::D     D:::::U   E::::::EEEEEEEEEE          SSSSSS::::S        SSSSSS::::S              T:::::T          H::::::HHHHH::::::H    E::::::EEEEEEEEEE        N::::::N   N:::::::::::N U:::::D     D:::::U M::::::M   M:::::::M   M::::::M  B::::B     B:::::B  E::::::EEEEEEEEEE     R::::R     R:::::R
G:::::G        G::::G U:::::D     D:::::U   E:::::E                         S:::::S            S:::::S             T:::::T          H:::::H     H:::::H    E:::::E                  N::::::N    N::::::::::N U:::::D     D:::::U M::::::M    M:::::M    M::::::M  B::::B     B:::::B  E:::::E               R::::R     R:::::R
 G:::::G       G::::G U::::::U   U::::::U   E:::::E       EEEEEE            S:::::S            S:::::S             T:::::T          H:::::H     H:::::H    E:::::E       EEEEEE     N::::::N     N:::::::::N U::::::U   U::::::U M::::::M     MMMMM     M::::::M  B::::B     B:::::B  E:::::E       EEEEEE  R::::R     R:::::R
  G:::::GGGGGGGG::::G U:::::::UUU:::::::U EE::::::EEEEEEEE:::::ESSSSSSS     S:::::SSSSSSSS     S:::::S           TT:::::::TT      HH::::::H     H::::::HHEE::::::EEEEEEEE:::::E     N::::::N      N::::::::N U:::::::UUU:::::::U M::::::M               M::::::MBB:::::BBBBBB::::::BEE::::::EEEEEEEE:::::ERR:::::R     R:::::R
   GG:::::::::::::::G  UU:::::::::::::UU  E::::::::::::::::::::ES::::::SSSSSS:::::SS::::::SSSSSS:::::S           T:::::::::T      H:::::::H     H:::::::HE::::::::::::::::::::E     N::::::N       N:::::::N  UU:::::::::::::UU  M::::::M               M::::::MB:::::::::::::::::B E::::::::::::::::::::ER::::::R     R:::::R
     GGG::::::GGG:::G    UU:::::::::UU    E::::::::::::::::::::ES:::::::::::::::SS S:::::::::::::::SS            T:::::::::T      H:::::::H     H:::::::HE::::::::::::::::::::E     N::::::N        N::::::N    UU:::::::::UU    M::::::M               M::::::MB::::::::::::::::B  E::::::::::::::::::::ER::::::R     R:::::R
        GGGGGG   GGGG      UUUUUUUUU      EEEEEEEEEEEEEEEEEEEEEE SSSSSSSSSSSSSSS    SSSSSSSSSSSSSSS              TTTTTTTTTTT      HHHHHHHHH     HHHHHHHHHEEEEEEEEEEEEEEEEEEEEEE     NNNNNNNN         NNNNNNN      UUUUUUUUU      MMMMMMMM               MMMMMMMMBBBBBBBBBBBBBBBBB   EEEEEEEEEEEEEEEEEEEEEERRRRRRRR     RRRRRRR
                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                              """